---
- name: Gather system info
  hosts: "dc01-cfw01"
  connection: local

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Export configuration
      paloaltonetworks.panos.panos_export:
        provider: '{{ provider }}'
        category: 'configuration'
        filename: 'running-config.xml'
      register: export_result

    - name: Format XML with 2-space indent
      command: "xmllint --format running-config.xml --output running-config.xml"